/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import CLASS.Login;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author vaish
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    Login l;
    public MainJFrame(Login l) {
        initComponents();
        
        this.l=l;
        
    CardLayout cardLayout = new CardLayout();
    maincard.setLayout(cardLayout);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        btnpatient = new javax.swing.JButton();
        btnemergency = new javax.swing.JButton();
        btnconsent = new javax.swing.JButton();
        btnfeedback = new javax.swing.JButton();
        btnbilling = new javax.swing.JButton();
        btninsurance = new javax.swing.JButton();
        btnibenefits = new javax.swing.JButton();
        btnpolicybenefits = new javax.swing.JButton();
        btnphysician = new javax.swing.JButton();
        btnspeciality = new javax.swing.JButton();
        btnpspeciality = new javax.swing.JButton();
        btnappointment = new javax.swing.JButton();
        btnrecords = new javax.swing.JButton();
        btnmedication = new javax.swing.JButton();
        btnprecription = new javax.swing.JButton();
        btnimmunizations = new javax.swing.JButton();
        btnlabtest = new javax.swing.JButton();
        btndiagnosis = new javax.swing.JButton();
        btntestresult = new javax.swing.JButton();
        btntraetment = new javax.swing.JButton();
        maincard = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        btnpatient.setBackground(new java.awt.Color(0, 0, 0));
        btnpatient.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        btnpatient.setForeground(new java.awt.Color(255, 255, 255));
        btnpatient.setText("PATIENT");
        btnpatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpatientActionPerformed(evt);
            }
        });

        btnemergency.setBackground(new java.awt.Color(0, 0, 0));
        btnemergency.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        btnemergency.setForeground(new java.awt.Color(255, 255, 255));
        btnemergency.setText("EMERGENCY CONTACT");
        btnemergency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnemergencyActionPerformed(evt);
            }
        });

        btnconsent.setBackground(new java.awt.Color(0, 0, 0));
        btnconsent.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        btnconsent.setForeground(new java.awt.Color(255, 255, 255));
        btnconsent.setText("CONSENT FORM");
        btnconsent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconsentActionPerformed(evt);
            }
        });

        btnfeedback.setBackground(new java.awt.Color(0, 0, 0));
        btnfeedback.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        btnfeedback.setForeground(new java.awt.Color(255, 255, 255));
        btnfeedback.setText("PATIENT FEEDBACK");
        btnfeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfeedbackActionPerformed(evt);
            }
        });

        btnbilling.setBackground(new java.awt.Color(0, 0, 0));
        btnbilling.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        btnbilling.setForeground(new java.awt.Color(255, 255, 255));
        btnbilling.setText("BILLING");
        btnbilling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbillingActionPerformed(evt);
            }
        });

        btninsurance.setBackground(new java.awt.Color(0, 0, 0));
        btninsurance.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        btninsurance.setForeground(new java.awt.Color(255, 255, 255));
        btninsurance.setText("INSURANCE POLICY");
        btninsurance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninsuranceActionPerformed(evt);
            }
        });

        btnibenefits.setBackground(new java.awt.Color(0, 0, 0));
        btnibenefits.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        btnibenefits.setForeground(new java.awt.Color(255, 255, 255));
        btnibenefits.setText("INSURANCE BENEFITS");
        btnibenefits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnibenefitsActionPerformed(evt);
            }
        });

        btnpolicybenefits.setBackground(new java.awt.Color(0, 0, 0));
        btnpolicybenefits.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        btnpolicybenefits.setForeground(new java.awt.Color(255, 255, 255));
        btnpolicybenefits.setText("POLICY BENEFITS");
        btnpolicybenefits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpolicybenefitsActionPerformed(evt);
            }
        });

        btnphysician.setBackground(new java.awt.Color(0, 0, 0));
        btnphysician.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        btnphysician.setForeground(new java.awt.Color(255, 255, 255));
        btnphysician.setText("PHYSICIAN");
        btnphysician.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnphysicianActionPerformed(evt);
            }
        });

        btnspeciality.setBackground(new java.awt.Color(0, 0, 0));
        btnspeciality.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        btnspeciality.setForeground(new java.awt.Color(255, 255, 255));
        btnspeciality.setText("SPECIALITY");
        btnspeciality.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnspecialityActionPerformed(evt);
            }
        });

        btnpspeciality.setBackground(new java.awt.Color(0, 0, 0));
        btnpspeciality.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        btnpspeciality.setForeground(new java.awt.Color(255, 255, 255));
        btnpspeciality.setText("PHYSICIAN SPECIALITY");
        btnpspeciality.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpspecialityActionPerformed(evt);
            }
        });

        btnappointment.setBackground(new java.awt.Color(0, 0, 0));
        btnappointment.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        btnappointment.setForeground(new java.awt.Color(255, 255, 255));
        btnappointment.setText("APPOINTMENT");
        btnappointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnappointmentActionPerformed(evt);
            }
        });

        btnrecords.setBackground(new java.awt.Color(0, 0, 0));
        btnrecords.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        btnrecords.setForeground(new java.awt.Color(255, 255, 255));
        btnrecords.setText("MEDICAL RECORDS");
        btnrecords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrecordsActionPerformed(evt);
            }
        });

        btnmedication.setBackground(new java.awt.Color(0, 0, 0));
        btnmedication.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        btnmedication.setForeground(new java.awt.Color(255, 255, 255));
        btnmedication.setText("MEDICATION");
        btnmedication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmedicationActionPerformed(evt);
            }
        });

        btnprecription.setBackground(new java.awt.Color(0, 0, 0));
        btnprecription.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        btnprecription.setForeground(new java.awt.Color(255, 255, 255));
        btnprecription.setText("PRESCRIPTION");
        btnprecription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprecriptionActionPerformed(evt);
            }
        });

        btnimmunizations.setBackground(new java.awt.Color(0, 0, 0));
        btnimmunizations.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        btnimmunizations.setForeground(new java.awt.Color(255, 255, 255));
        btnimmunizations.setText("IMMUNIZATIONS");
        btnimmunizations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnimmunizationsActionPerformed(evt);
            }
        });

        btnlabtest.setBackground(new java.awt.Color(0, 0, 0));
        btnlabtest.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        btnlabtest.setForeground(new java.awt.Color(255, 255, 255));
        btnlabtest.setText("LAB TEST");
        btnlabtest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlabtestActionPerformed(evt);
            }
        });

        btndiagnosis.setBackground(new java.awt.Color(0, 0, 0));
        btndiagnosis.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        btndiagnosis.setForeground(new java.awt.Color(255, 255, 255));
        btndiagnosis.setText("DIAGNOSIS");
        btndiagnosis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndiagnosisActionPerformed(evt);
            }
        });

        btntestresult.setBackground(new java.awt.Color(0, 0, 0));
        btntestresult.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        btntestresult.setForeground(new java.awt.Color(255, 255, 255));
        btntestresult.setText("TEST RESULT");
        btntestresult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntestresultActionPerformed(evt);
            }
        });

        btntraetment.setBackground(new java.awt.Color(0, 0, 0));
        btntraetment.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        btntraetment.setForeground(new java.awt.Color(255, 255, 255));
        btntraetment.setText("TREATMENT");
        btntraetment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntraetmentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnemergency)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnfeedback)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btninsurance)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnpolicybenefits))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnpatient)
                        .addGap(26, 26, 26)
                        .addComponent(btnconsent)
                        .addGap(18, 18, 18)
                        .addComponent(btnbilling)
                        .addGap(18, 18, 18)
                        .addComponent(btnibenefits)
                        .addGap(18, 18, 18)
                        .addComponent(btnphysician)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnspeciality)
                        .addGap(18, 18, 18)
                        .addComponent(btnappointment)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnmedication)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnimmunizations)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btndiagnosis)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btntraetment))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnpspeciality)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnrecords)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnprecription)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnlabtest)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btntestresult)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnpatient)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnfeedback)
                            .addComponent(btnemergency)
                            .addComponent(btninsurance)
                            .addComponent(btnpolicybenefits)
                            .addComponent(btnspeciality)
                            .addComponent(btnappointment)
                            .addComponent(btnmedication)
                            .addComponent(btnimmunizations)
                            .addComponent(btndiagnosis)
                            .addComponent(btntraetment)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnconsent)
                            .addComponent(btnbilling)
                            .addComponent(btnibenefits)
                            .addComponent(btnphysician)
                            .addComponent(btnpspeciality)
                            .addComponent(btnrecords)
                            .addComponent(btnprecription)
                            .addComponent(btnlabtest)
                            .addComponent(btntestresult))
                        .addGap(0, 42, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jSplitPane1.setTopComponent(jPanel1);

        maincard.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout maincardLayout = new javax.swing.GroupLayout(maincard);
        maincard.setLayout(maincardLayout);
        maincardLayout.setHorizontalGroup(
            maincardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1405, Short.MAX_VALUE)
        );
        maincardLayout.setVerticalGroup(
            maincardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 605, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(maincard);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnrecordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrecordsActionPerformed
        // TODO add your handling code here:
        Medical m=new Medical(maincard,l);
        maincard.add("Medical",m);
        CardLayout cardlayout= (CardLayout) maincard.getLayout();
        cardlayout.next(maincard);
        
    }//GEN-LAST:event_btnrecordsActionPerformed

    private void btnlabtestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlabtestActionPerformed
        // TODO add your handling code here:
        LabTest p=new LabTest(maincard,l);
        maincard.add("LabTest",p);
        CardLayout cardlayout= (CardLayout) maincard.getLayout();
        cardlayout.next(maincard);
    }//GEN-LAST:event_btnlabtestActionPerformed

    private void btnpatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpatientActionPerformed
        // TODO add your handling code here:
         
         Patient p=new Patient(maincard,l);
        maincard.add("Patient",p);
        CardLayout cardlayout= (CardLayout) maincard.getLayout();
        cardlayout.next(maincard);
        
    }//GEN-LAST:event_btnpatientActionPerformed

    private void btnconsentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconsentActionPerformed
        // TODO add your handling code here:
        Consentform c=new Consentform(maincard,l);
        maincard.add("ConsentForm",c);
        CardLayout cardlayout= (CardLayout) maincard.getLayout();
        cardlayout.next(maincard);
    }//GEN-LAST:event_btnconsentActionPerformed

    private void btnemergencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnemergencyActionPerformed
        // TODO add your handling code here:
       EmergencyContact e=new EmergencyContact(maincard,l);
        maincard.add("Emergency Contact",e);
        CardLayout cardlayout= (CardLayout) maincard.getLayout();
        cardlayout.next(maincard);
    }//GEN-LAST:event_btnemergencyActionPerformed

    private void btnfeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfeedbackActionPerformed
        // TODO add your handling code here:
        PatientFeedback e=new PatientFeedback(maincard,l);
        maincard.add("PatientFeedback",e);
        CardLayout cardlayout= (CardLayout) maincard.getLayout();
        cardlayout.next(maincard);
    }//GEN-LAST:event_btnfeedbackActionPerformed

    private void btnbillingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbillingActionPerformed
        // TODO add your handling code here:
        
        Billing b=new Billing(maincard,l);
        maincard.add("Billing",b);
        CardLayout cardlayout= (CardLayout) maincard.getLayout();
        cardlayout.next(maincard);
    }//GEN-LAST:event_btnbillingActionPerformed

    private void btninsuranceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninsuranceActionPerformed
        // TODO add your handling code here:
        InsurancePolicy i=new InsurancePolicy(maincard,l);
        maincard.add("InsurancePolicy",i);
        CardLayout cardlayout= (CardLayout) maincard.getLayout();
        cardlayout.next(maincard);
    }//GEN-LAST:event_btninsuranceActionPerformed

    private void btnibenefitsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnibenefitsActionPerformed
        // TODO add your handling code here:
        InsuranceBenefits i=new InsuranceBenefits(maincard,l);
        maincard.add("InsuranceBenefits",i);
        CardLayout cardlayout= (CardLayout) maincard.getLayout();
        cardlayout.next(maincard);
    }//GEN-LAST:event_btnibenefitsActionPerformed

    private void btnpolicybenefitsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpolicybenefitsActionPerformed
        // TODO add your handling code here:
        PolicyBenefits i=new PolicyBenefits(maincard,l);
        maincard.add("PolicyBenefits",i);
        CardLayout cardlayout= (CardLayout) maincard.getLayout();
        cardlayout.next(maincard);
    }//GEN-LAST:event_btnpolicybenefitsActionPerformed

    private void btnphysicianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnphysicianActionPerformed
        // TODO add your handling code here:
        Physician p=new Physician(maincard,l);
        maincard.add("Physician",p);
        CardLayout cardlayout= (CardLayout) maincard.getLayout();
        cardlayout.next(maincard);
    }//GEN-LAST:event_btnphysicianActionPerformed

    private void btnpspecialityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpspecialityActionPerformed
        // TODO add your handling code here:
        PhysicianSpecialty p=new PhysicianSpecialty(maincard,l);
        maincard.add("PhysicianSpecialty",p);
        CardLayout cardlayout= (CardLayout) maincard.getLayout();
        cardlayout.next(maincard);
    }//GEN-LAST:event_btnpspecialityActionPerformed

    private void btnspecialityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnspecialityActionPerformed
        // TODO add your handling code here:
        Specialty p=new Specialty(maincard,l);
        maincard.add("Specialty",p);
        CardLayout cardlayout= (CardLayout) maincard.getLayout();
        cardlayout.next(maincard);
    }//GEN-LAST:event_btnspecialityActionPerformed

    private void btnappointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnappointmentActionPerformed
        // TODO add your handling code here:
        Appointment p=new Appointment(maincard,l);
        maincard.add("Appointment",p);
        CardLayout cardlayout= (CardLayout) maincard.getLayout();
        cardlayout.next(maincard);
    }//GEN-LAST:event_btnappointmentActionPerformed

    private void btnmedicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmedicationActionPerformed
        // TODO add your handling code here:
        Medication p=new Medication(maincard,l);
        maincard.add("Medication",p);
        CardLayout cardlayout= (CardLayout) maincard.getLayout();
        cardlayout.next(maincard);
    }//GEN-LAST:event_btnmedicationActionPerformed

    private void btnprecriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprecriptionActionPerformed
        // TODO add your handling code here:
        Prescription p=new Prescription(maincard,l);
        maincard.add("Prescription",p);
        CardLayout cardlayout= (CardLayout) maincard.getLayout();
        cardlayout.next(maincard);
    }//GEN-LAST:event_btnprecriptionActionPerformed

    private void btnimmunizationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnimmunizationsActionPerformed
        // TODO add your handling code here:
        Immunizations p=new Immunizations(maincard,l);
        maincard.add("Immunizations",p);
        CardLayout cardlayout= (CardLayout) maincard.getLayout();
        cardlayout.next(maincard);
    }//GEN-LAST:event_btnimmunizationsActionPerformed

    private void btndiagnosisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndiagnosisActionPerformed
        // TODO add your handling code here:
        Diagnosis p=new Diagnosis(maincard,l);
        maincard.add("Diagnosis",p);
        CardLayout cardlayout= (CardLayout) maincard.getLayout();
        cardlayout.next(maincard);
    }//GEN-LAST:event_btndiagnosisActionPerformed

    private void btntestresultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntestresultActionPerformed
        // TODO add your handling code here:
        TestResult p=new TestResult(maincard,l);
        maincard.add("TestResult",p);
        CardLayout cardlayout= (CardLayout) maincard.getLayout();
        cardlayout.next(maincard);
    }//GEN-LAST:event_btntestresultActionPerformed

    private void btntraetmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntraetmentActionPerformed
        // TODO add your handling code here:
        Treatment p=new Treatment(maincard,l);
        maincard.add("Treatment",p);
        CardLayout cardlayout= (CardLayout) maincard.getLayout();
        cardlayout.next(maincard);
    }//GEN-LAST:event_btntraetmentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Login existingInstance = Login.getInstance();
                new MainJFrame(existingInstance).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnappointment;
    private javax.swing.JButton btnbilling;
    private javax.swing.JButton btnconsent;
    private javax.swing.JButton btndiagnosis;
    private javax.swing.JButton btnemergency;
    private javax.swing.JButton btnfeedback;
    private javax.swing.JButton btnibenefits;
    private javax.swing.JButton btnimmunizations;
    private javax.swing.JButton btninsurance;
    private javax.swing.JButton btnlabtest;
    private javax.swing.JButton btnmedication;
    private javax.swing.JButton btnpatient;
    private javax.swing.JButton btnphysician;
    private javax.swing.JButton btnpolicybenefits;
    private javax.swing.JButton btnprecription;
    private javax.swing.JButton btnpspeciality;
    private javax.swing.JButton btnrecords;
    private javax.swing.JButton btnspeciality;
    private javax.swing.JButton btntestresult;
    private javax.swing.JButton btntraetment;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel maincard;
    // End of variables declaration//GEN-END:variables
}
