/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import CLASS.Login;
import java.sql.Statement;
import java.util.Date;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import javax.swing.JPanel;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author vaish
 */
public class Medical extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    
    private JPanel maincard;
    private Login l;
    
    public Medical(JPanel maicard, Login l) {
        initComponents();
        
        this.maincard=maincard;
        this.l=l;
        
        txtdiabetic.setEnabled(false);
        
    }
    
     String driver= "com.microsoft.sqlserver.jdbc.SQLServerDriver";
    String url= "jdbc:sqlserver://localhost:1433;databaseName=PATIENTMANAGEMENT;encrypt=true;trustServerCertificate=true;";
    String user="sa";
    String password="sa";
    
    Statement st;
    ResultSet rs;
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jdate = new com.toedter.calendar.JDateChooser();
        no = new javax.swing.JRadioButton();
        yes = new javax.swing.JRadioButton();
        txtblood = new javax.swing.JTextField();
        txtdiabetic = new javax.swing.JTextField();
        txtallergies = new javax.swing.JTextField();
        txtpatient = new javax.swing.JTextField();
        txtpressure = new javax.swing.JTextField();
        txtinvoice = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btninsert = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1230, 700));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 255));
        jLabel1.setText("MEDICAL RECORD");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(504, 6, 228, -1));

        jLabel3.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("PATIENT ID");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 150, -1));

        jLabel4.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("INVOICE ID");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 150, -1));

        jLabel5.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("DATE OF ENTRY");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 180, -1));

        jLabel6.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("BLOOD GROUP");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 170, -1));

        jLabel7.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("ALLERGIES");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 150, -1));

        jLabel8.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("DIABETIC");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 140, -1));

        jLabel9.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("BLOOD PRESSURE");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 200, -1));
        add(jdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 220, 205, 31));

        no.setBackground(new java.awt.Color(153, 0, 255));
        buttonGroup1.add(no);
        no.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        no.setForeground(new java.awt.Color(255, 255, 255));
        no.setText("NO");
        no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noActionPerformed(evt);
            }
        });
        add(no, new org.netbeans.lib.awtextra.AbsoluteConstraints(522, 455, -1, -1));

        yes.setBackground(new java.awt.Color(153, 0, 255));
        buttonGroup1.add(yes);
        yes.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        yes.setForeground(new java.awt.Color(255, 255, 255));
        yes.setText("YES");
        yes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesActionPerformed(evt);
            }
        });
        add(yes, new org.netbeans.lib.awtextra.AbsoluteConstraints(416, 455, -1, -1));

        txtblood.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        add(txtblood, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 285, 205, 30));

        txtdiabetic.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        txtdiabetic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdiabeticActionPerformed(evt);
            }
        });
        add(txtdiabetic, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 414, 205, 30));

        txtallergies.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        add(txtallergies, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 353, 205, 30));

        txtpatient.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        add(txtpatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 111, 205, 30));

        txtpressure.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        add(txtpressure, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 484, 205, 30));

        txtinvoice.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        add(txtinvoice, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 172, 205, 30));

        jTable1.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Record ID", "Patient ID", "Invoice ID", "Date of Entry", "Blood Group", "Allergies", "Diabetic", "Blood Pressure"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(584, 49, 650, 607));

        btninsert.setBackground(new java.awt.Color(153, 0, 255));
        btninsert.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        btninsert.setForeground(new java.awt.Color(255, 255, 255));
        btninsert.setText("INSERT");
        btninsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninsertActionPerformed(evt);
            }
        });
        add(btninsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 556, 137, 34));

        btnupdate.setBackground(new java.awt.Color(153, 0, 255));
        btnupdate.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        btnupdate.setForeground(new java.awt.Color(255, 255, 255));
        btnupdate.setText("UPDATE");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        add(btnupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 556, 140, 34));

        btndelete.setBackground(new java.awt.Color(153, 0, 255));
        btndelete.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        btndelete.setForeground(new java.awt.Color(255, 255, 255));
        btndelete.setText("DELETE");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        add(btndelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 623, 137, 33));

        btnclear.setBackground(new java.awt.Color(153, 0, 255));
        btnclear.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        btnclear.setForeground(new java.awt.Color(255, 255, 255));
        btnclear.setText("VIEW");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });
        add(btnclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 623, 140, 33));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/diagnosis.png"))); // NOI18N
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 490, 540));
    }// </editor-fold>//GEN-END:initComponents

    private void noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noActionPerformed
        // TODO add your handling code here:
        txtdiabetic.setText("0");
    }//GEN-LAST:event_noActionPerformed

    private void yesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesActionPerformed
        // TODO add your handling code here:
        txtdiabetic.setText("1");
    }//GEN-LAST:event_yesActionPerformed

    private void txtdiabeticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdiabeticActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtdiabeticActionPerformed

    private void btninsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninsertActionPerformed
        // TODO add your handling code here:
        try
        {
            Class.forName(driver);
            Connection conn=DriverManager.getConnection(url,user,password);

            if(txtpatient.getText().isEmpty() || txtinvoice.getText().isEmpty() ||jdate.getDate() == null ||  txtblood.getText().isEmpty() ||txtallergies.getText().isEmpty() ||txtdiabetic.getText().isEmpty() ||txtpressure.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(this, "Empty fields encountered");
                return;
            }

            String formattedDate = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(jdate.getDate());

            String sql = "INSERT INTO MedicalRecords (PatientID, InvoiceID, DateOfEntry, BloodGroup, Allergies, Diabetic, BloodPressure) VALUES " +
            "('" + txtpatient.getText() + "','" + txtinvoice.getText() + "','" + formattedDate + "','" + txtblood.getText() + "','" +
            txtallergies.getText() + "','" + txtdiabetic.getText() + "','" + txtpressure.getText() + "')";

            st=conn.createStatement();
            st.execute(sql);

            JOptionPane.showMessageDialog(this, "Inserted Successfully");
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btninsertActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
        try
        {
            Class.forName(driver);
            Connection conn=DriverManager.getConnection(url,user,password);

            int selectedRowIndex = jTable1.getSelectedRow();

            if (selectedRowIndex == -1) {
                JOptionPane.showMessageDialog(this, "Please select a row to update");
                return;
            }

            if(txtpatient.getText().isEmpty() || txtinvoice.getText().isEmpty() ||jdate.getDate() == null ||  txtblood.getText().isEmpty() ||txtallergies.getText().isEmpty() ||txtdiabetic.getText().isEmpty() ||txtpressure.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(this, "Empty fields encountered");
                return;
            }

            Object selectedValue = jTable1.getValueAt(selectedRowIndex, 0);
            String formattedDate = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(jdate.getDate());

            String sql = "UPDATE MedicalRecords SET " +
            "PatientID = '" + txtpatient.getText() + "', " +
            "InvoiceID = '" + txtinvoice.getText() + "', " +
            "DateOfEntry = '" + formattedDate + "', " +
            "BloodGroup = '" + txtblood.getText() + "', " +
            "Allergies = '" + txtallergies.getText() + "', " +
            "Diabetic = '" + txtdiabetic.getText() + "', " +
            "BloodPressure = '" + txtpressure.getText() + "' " +
            "WHERE RecordID = '" + selectedValue + "'";

            st=conn.createStatement();

            int rowsUpdated = st.executeUpdate(sql);

            if (rowsUpdated > 0) {
                JOptionPane.showMessageDialog(this, "Updated Successfully");
            } else {
                JOptionPane.showMessageDialog(this, "Update failed");
            }
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        try
        {
            Class.forName(driver);
            Connection conn=DriverManager.getConnection(url,user,password);

            int selectedRowIndex = jTable1.getSelectedRow();

            if (selectedRowIndex == -1) {
                JOptionPane.showMessageDialog(this, "Please select a row to delete");
                return;
            }

            Object selectedValue = jTable1.getValueAt(selectedRowIndex, 0);

            String sql = "DELETE FROM MedicalRecords WHERE RecordID = '" + selectedValue + "'";

            st = conn.createStatement();

            int rowsDeleted = st.executeUpdate(sql);

            if (rowsDeleted > 0) {
                JOptionPane.showMessageDialog(this, "Deleted Successfully");
            } else {
                JOptionPane.showMessageDialog(this, "Delete failed");
            }
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        // TODO add your handling code here:
        try
        {
            Class.forName(driver);
            Connection conn=DriverManager.getConnection(url,user,password);

            String sql = "select * from MedicalRecords";

            st=conn.createStatement();
            rs=st.executeQuery(sql);

            jTable1.setModel(DbUtils.resultSetToTableModel(rs));

        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnclearActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btninsert;
    private javax.swing.JButton btnupdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private com.toedter.calendar.JDateChooser jdate;
    private javax.swing.JRadioButton no;
    private javax.swing.JTextField txtallergies;
    private javax.swing.JTextField txtblood;
    private javax.swing.JTextField txtdiabetic;
    private javax.swing.JTextField txtinvoice;
    private javax.swing.JTextField txtpatient;
    private javax.swing.JTextField txtpressure;
    private javax.swing.JRadioButton yes;
    // End of variables declaration//GEN-END:variables
}
