/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;
import CLASS.Login;
import java.sql.Statement;
import java.util.Date;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import javax.swing.JPanel;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author vaish
 */
public class Physician extends javax.swing.JPanel {

    /**
     * Creates new form Physician
     */
    
            private JPanel maincard;
    private Login l;
    
    public Physician(JPanel maicard, Login l) {
        initComponents();
        
                this.maincard=maincard;
        this.l=l;
    }
    
        String driver= "com.microsoft.sqlserver.jdbc.SQLServerDriver";
    String url= "jdbc:sqlserver://localhost:1433;databaseName=PATIENTMANAGEMENT;encrypt=true;trustServerCertificate=true;";
    String user="sa";
    String password="sa";
    
     Statement st;
    ResultSet rs;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtnumber = new javax.swing.JTextField();
        txtlicense = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btninsert = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        txtday = new javax.swing.JTextField();
        txttime = new javax.swing.JTextField();
        joinidate = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtlast = new javax.swing.JTextField();
        txtfirst = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtsupervisor = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 255));
        jLabel1.setText("PHYSICIAN");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 140, -1));

        jLabel5.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("JOINING DATE");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 120, 40));

        jLabel7.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("LICENSE NUMBER");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 130, 40));

        jLabel8.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("CONTACT NUMBER");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 140, 40));

        jLabel9.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("SHIFT DAY");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 110, 40));

        jLabel12.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("SHIFT TIME");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 100, -1));

        txtnumber.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        txtnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnumberActionPerformed(evt);
            }
        });
        add(txtnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 205, 30));

        txtlicense.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        add(txtlicense, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 205, 30));

        jTable1.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "FIRST", "LAST", "LICENSE", "CONTACT", "SHIFT DAY", "SHIFT TIME", "JOIN DATE", "SUPERVISOR", "FULL NAME"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 9, 810, 650));

        btninsert.setBackground(new java.awt.Color(153, 0, 255));
        btninsert.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        btninsert.setForeground(new java.awt.Color(255, 255, 255));
        btninsert.setText("INSERT");
        btninsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninsertActionPerformed(evt);
            }
        });
        add(btninsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, 137, 34));

        btnupdate.setBackground(new java.awt.Color(153, 0, 255));
        btnupdate.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        btnupdate.setForeground(new java.awt.Color(255, 255, 255));
        btnupdate.setText("UPDATE");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        add(btnupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 510, 140, 34));

        btndelete.setBackground(new java.awt.Color(153, 0, 255));
        btndelete.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        btndelete.setForeground(new java.awt.Color(255, 255, 255));
        btndelete.setText("DELETE");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        add(btndelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 590, 137, 33));

        btnclear.setBackground(new java.awt.Color(153, 0, 255));
        btnclear.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        btnclear.setForeground(new java.awt.Color(255, 255, 255));
        btnclear.setText("VIEW");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });
        add(btnclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 590, 140, 33));

        txtday.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        add(txtday, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 205, 30));

        txttime.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        add(txttime, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 205, 30));
        add(joinidate, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, 200, 31));

        jLabel10.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("FIRST NAME");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 100, 40));

        jLabel11.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("LAST NAME");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 100, 40));

        txtlast.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        txtlast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlastActionPerformed(evt);
            }
        });
        add(txtlast, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 205, 30));

        txtfirst.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        add(txtfirst, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 205, 30));

        jLabel13.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("SUPERVISOR");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 100, -1));

        txtsupervisor.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        add(txtsupervisor, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, 205, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void txtnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnumberActionPerformed

    private void btninsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninsertActionPerformed
        // TODO add your handling code here:
        try
        {
            Class.forName(driver);
            Connection conn=DriverManager.getConnection(url,user,password);

            if(txtfirst.getText().isEmpty() || txtlast.getText().isEmpty() ||txtlicense.getText().isEmpty() || txtnumber.getText().isEmpty() || txtday.getText().isEmpty() || txttime.getText().isEmpty() || joinidate==null||txtsupervisor.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(this, "Empty fields encountered");
                return;
            }
            String formattedDate2 = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(joinidate.getDate());

            String sql = "INSERT INTO Physician (FirstName, LastName, LicenseNumber, ContactNumber, ShiftDay,ShiftTime,JoiningDate,Supervisor) VALUES " +
            "('" + txtfirst.getText() + "','" + txtlast.getText() + "','" +
            txtlicense.getText() + "','" + txtnumber.getText() + "','" + txtday.getText() +"','"+ txttime.getText() +"','"+formattedDate2 + "','" +txtsupervisor + "')";

            st=conn.createStatement();
            st.execute(sql);

            JOptionPane.showMessageDialog(this, "Inserted Successfully");
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btninsertActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
        try
        {
            Class.forName(driver);
            Connection conn=DriverManager.getConnection(url,user,password);

            int selectedRowIndex = jTable1.getSelectedRow();

            if (selectedRowIndex == -1) {
                JOptionPane.showMessageDialog(this, "Please select a row to update");
                return;
            }

             if(txtfirst.getText().isEmpty() || txtlast.getText().isEmpty() ||txtlicense.getText().isEmpty() || txtnumber.getText().isEmpty() || txtday.getText().isEmpty() || txttime.getText().isEmpty() || joinidate==null||txtsupervisor.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(this, "Empty fields encountered");
                return;
            }

            Object selectedValue = jTable1.getValueAt(selectedRowIndex, 0);
            String formattedDate2 = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(joinidate.getDate());

            String sql = "UPDATE Physician SET " +
            "FirstName = '" + txtfirst.getText() + "', " +
            "LastName = '" + txtlast.getText() + "', " +
            "LicenseNumber = '" + txtlicense.getText() + "', " +
            "ContactNumber = '" + txtnumber.getText() + "', " +
            "ShiftDay = '" + txtday.getText() + "', " +
            "ShiftTime = '" + txttime.getText() + "', " +
            "JoiningDate = '" + formattedDate2 + "', " +
            "Supervisor = '" + txtsupervisor.getText() + "', " +
            "WHERE PhysicianID = " + selectedValue;

            st=conn.createStatement();

            int rowsUpdated = st.executeUpdate(sql);

            if (rowsUpdated > 0) {
                JOptionPane.showMessageDialog(this, "Updated Successfully");
            } else {
                JOptionPane.showMessageDialog(this, "Update failed");
            }
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        try
        {
            Class.forName(driver);
            Connection conn=DriverManager.getConnection(url,user,password);

            int selectedRowIndex = jTable1.getSelectedRow();

            if (selectedRowIndex == -1) {
                JOptionPane.showMessageDialog(this, "Please select a row to delete");
                return;
            }

            Object selectedValue = jTable1.getValueAt(selectedRowIndex, 0);

            String sql = "DELETE FROM Physician WHERE PhysicianID = '" + selectedValue + "'";

            st = conn.createStatement();

            int rowsDeleted = st.executeUpdate(sql);

            if (rowsDeleted > 0) {
                JOptionPane.showMessageDialog(this, "Deleted Successfully");
            } else {
                JOptionPane.showMessageDialog(this, "Delete failed");
            }
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        // TODO add your handling code here:
        try
        {
            Class.forName(driver);
            Connection conn=DriverManager.getConnection(url,user,password);

            String sql = "select * from Physician";

            st=conn.createStatement();
            rs=st.executeQuery(sql);

            jTable1.setModel(DbUtils.resultSetToTableModel(rs));

        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnclearActionPerformed

    private void txtlastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlastActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlastActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btninsert;
    private javax.swing.JButton btnupdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private com.toedter.calendar.JDateChooser joinidate;
    private javax.swing.JTextField txtday;
    private javax.swing.JTextField txtfirst;
    private javax.swing.JTextField txtlast;
    private javax.swing.JTextField txtlicense;
    private javax.swing.JTextField txtnumber;
    private javax.swing.JTextField txtsupervisor;
    private javax.swing.JTextField txttime;
    // End of variables declaration//GEN-END:variables
}
